### ISSUE TITLE
installing Spaniel on MacOS Mojave 10.14.6

### ISSUE THREAD

**Issue by alikhuseynov** [RachelQueen1/Spaniel#1]
Hi Rachel,
Frirst, thanks a lot for this package, very useful than stand-alone software for Spatial Transcriptomics. I was trying to install your R package on recent MacOS Mojave. The suggested installation in README.md did not work, so after some debugging, here is how I could install it:

#### make sure you have R version 3.6

install the relevant packages
```{r install_packages1, include=FALSE}
install.packages("devtools",repos = "http://cran.us.r-project.org")
install.packages("Seurat",repos = "http://cran.us.r-project.org")
install.packages("BiocManager",repos = "http://cran.us.r-project.org")
BiocManager::install(version = "devel")
BiocManager::install(c("SingleCellExperiment","scater"))
devtools::install_github("rstudio/rmarkdown")
install.packages('knitr', repos = c("http://cran.rstudio.org"),type = "source")
```

#### install Spaniel package for Spatial Transcriptomics
```{r install_packages3, include=FALSE}
devtools::install_github(repo = "RachelQueen1/Spaniel", build_opts = c("--no-resave-data", "--no-manual"), build_vignettes = TRUE)
```
The main problem was the different R versions required for scater, SingleCellExperiment (3.8 is for R 3.5) and the current Spaniel is using R 3.6. 
Probably you could edit your README.md for other users who would definitely use this package.

Thanks
Alik

**Comment by RachelQueen1** [comment]
Hi Alik, 

Thanks for testing out Spaniel and sorry you have had trouble installing it. I have been working on submitting the package to Bioconductor which meant I had to change some of the dependencies in the process. I will update the README. I'd be interested in you have any other suggestions for improvements.

Best wishes, 

Rachel

**Comment by alikhuseynov** [comment]
Hi Rachel
No problem, I could install and start using it. I think I would just fork Spaniel repo, make some changes etc.. and then you can decide if you want to have them in your primary repo?
Very useful package, came out just in the right time! :)

**Comment by RachelQueen1** [comment]
Thank you, glad it is of use :) yes if you wanted to fork the repo I would be happy to look at your suggestions
